M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Tue 01 Mar 2022 01:47:03 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-01T13:47:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.986
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.988
%
G90
G05
T1
X132.11Y-56.305
X137.89Y-56.305
T2
X120.5Y-52.17
X123.5Y-52.17
T3
X126.684Y-56.59
X128.716Y-56.59
T4
X127.7Y-51.51
T0
M30
