M48
; DRILL file {KiCad (7.0.0)} date Thu Jun  1 21:15:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-01T21:15:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0389
%
G90
G05
T1
X5.2012Y-2.2167
X5.4287Y-2.2167
T2
X4.7441Y-2.0539
X4.8622Y-2.0539
T3
X4.9876Y-2.228
X5.0676Y-2.228
T4
X5.0276Y-2.028
T0
M30
